# Site wide configuration

title: chroni - Tech Chronicles 
description: "Chronicle, Blog and Daily Hacks"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://chroni.de

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: Toni und Christian
name: Admin
web: http://chroni.de
email: mail@chroni.de
twitter: 
bio: 
avatar: bio-photo.jpg # 160x160 px image for author byline
google:
plus: 


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]